### ISSUE TITLE
Error: Cannot find module 'iconv-lite'

### ISSUE THREAD

**Issue by x5engine** [webhacking/url-metadata-parser#1]
If you try this package on https://npm.runkit.com/url-metadata-parser

you will get that error

`Error: Cannot find module 'iconv-lite'`

why is that not available ?

maybe it is just related to runkit?

thanks for this package.

**Comment by webhacking** [comment]
Hi, @x5engine 
I'm sorry that you had to wait so much time for the answer. 
Now you can parse like below. (And update new apis plz checkout readme.md)

```javascript
import {UrlMetadataParser} from './url-metadata-parser';

UrlMetadataParser.parse('https://www.hax0r.info').toPromise().then(metadata => {
  const origin = metadata.getContentByName('Referrer');
  const author = metadata.getContentByName('author');
});
```

And i think runkit actually missing iconv-lite.

**Comment by webhacking** [comment]
@x5engine Everythings fine checkout below.
https://travis-ci.org/webhacking/url-metadata-parser
